name: cffconvert

on: push

jobs:

  cffconvert:
    name: Verify citation metadata consistency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out a copy of the repository

      - uses: citation-file-format/cffconvert-github-action@main
        name: Check whether the citation metadata from CITATION.cff is equivalent to that in .zenodo.json
